import type { Metadata } from "next";
import SessionProvider from "@/components/SessionProvider"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { session, ...params },
}: any) {
  return (
    <html lang="en">
      <body>
      <SessionProvider session={session}>
        {children}
      </SessionProvider>
      </body>
    </html>
  );
}
